// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movian.Business.EnumTypes;
using Movian.Data.Contexts;

#nullable disable

namespace Movian.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220904015056_AdjustedPropertyName")]
    partial class AdjustedPropertyName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Movian.Business.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id_Address");

                    b.Property<string>("AdditionalAddressData")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id_Supplier");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id")
                        .HasName("Id_Address");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("TB_Address", (string)null);
                });

            modelBuilder.Entity("Movian.Business.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id_Product");

                    b.Property<bool>("Active")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id_Supplier");

                    b.Property<decimal>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id")
                        .HasName("Id_Product");

                    b.HasIndex("SupplierId");

                    b.ToTable("TB_Products", (string)null);
                });

            modelBuilder.Entity("Movian.Business.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id_Supplier");

                    b.Property<bool>("Active")
                        .HasColumnType("integer");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id_Address");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<SupplierType>("SupplierType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("Id_Supplier");

                    b.ToTable("TB_Supplier", (string)null);
                });

            modelBuilder.Entity("Movian.Business.Models.Address", b =>
                {
                    b.HasOne("Movian.Business.Models.Supplier", "Supplier")
                        .WithOne("Address")
                        .HasForeignKey("Movian.Business.Models.Address", "SupplierId")
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Movian.Business.Models.Product", b =>
                {
                    b.HasOne("Movian.Business.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Movian.Business.Models.Supplier", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
